# Generated by Django 5.2.8 on 2026-05-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_alter_stock_options_remove_stock_new_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='stock',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
