# Generated by Django 5.2.8 on 2026-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_billitem_item_total_alter_billitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
