# Generated by Django 5.2.8 on 2026-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0006_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
