# Generated by Django 5.2.8 on 2026-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0007_bill_bill_sequence_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of this item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('box', 'Box'), ('case', 'Case'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('dozen', 'Dozen'), ('pack', 'Pack')], default='piece', help_text='Unit of measurement', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('box', 'Box'), ('case', 'Case'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('dozen', 'Dozen'), ('pack', 'Pack')], default='piece', help_text='Unit of measurement', max_length=20),
        ),
    ]
