# Generated by Django 5.2.8 on 2026-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0008_billitem_unit_product_unit_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('box', 'Box'), ('case', 'Case'), ('packet', 'Packet')], default='piece', help_text='Unit of measurement', max_length=20),
        ),
    ]
