# Generated by Django 5.2.8 on 2026-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0009_alter_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('packet', 'Packet'), ('piece', 'Piece'), ('box', 'Box'), ('case', 'Case')], default='piece', help_text='Unit of measurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('packet', 'Packet'), ('piece', 'Piece'), ('box', 'Box'), ('case', 'Case')], default='piece', help_text='Unit of measurement', max_length=20),
        ),
    ]
