# Generated by Django 5.2.8 on 2026-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0010_alter_product_unit_alter_stock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
