# Generated by Django 5.2.8 on 2026-05-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0012_remove_bill_gstin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='gst_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gstin',
        ),
    ]
