# Generated by Django 5.2.8 on 2026-05-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0013_remove_bill_gst_amount_remove_bill_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
    ]
