# Generated by Django 5.2.8 on 2026-05-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0014_bill_gst_amount_bill_gst_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='gst_rate',
        ),
    ]
